### ISSUE TITLE
Colab support?

### ISSUE THREAD

**Issue by kylebarron** [Kirill888/jupyter-ui-poll#18]
👋  This is an awesome library, thanks for writing it!

I'm curious if you've thought at all or attempted supporting Colab as well. If you open your existing [binder notebook in Colab](https://colab.research.google.com/github/Kirill888/jupyter-ui-poll/blob/develop/notebooks/Examples.ipynb) and try to run it there are a couple errors:

1.
	  ```
	  Error in callback <bound method KernelWrapper._post_run_cell_hook of <jupyter_ui_poll._poll.KernelWrapper object at 0x7f980abfba10>> (for post_run_cell):
	  ---------------------------------------------------------------------------
	  TypeError                                 Traceback (most recent call last)
	  TypeError: _post_run_cell_hook() missing 1 required positional argument: '_'
	  ```

	It looks like that can be solved by setting `_=None` here https://github.com/Kirill888/jupyter-ui-poll/blob/9da1126d8e1e9ca4966a7f6f8089f0dfb231f2ca/jupyter_ui_poll/_poll.py#L114 or switching to `_post_run_cell_hook(self, *args, **kwargs):` since you don't use any arguments.

2. 
    
    ```
	  ---------------------------------------------------------------------------
	  TypeError                                 Traceback (most recent call last)
	  <ipython-input-3-34af5bb52bd8> in <module>()
	        6     while int(btn.description) < 10:
	        7         print(btn.description, end="")
	  ----> 8         ui_poll(11)  # Process upto 11 ui events per iteration
	        9         time.sleep(0.1)
	       10 
	  
	  4 frames
	  /usr/local/lib/python3.7/dist-packages/jupyter_ui_poll/_async_thread.py in sync_func(*args, **kwargs)
	       40     def wrap(self, func):
	       41         def sync_func(*args, **kwargs):
	  ---> 42             return self.submit(func, *args, **kwargs).result()
	       43 
	       44         return sync_func
	  
	  /usr/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
	      433                 raise CancelledError()
	      434             elif self._state == FINISHED:
	  --> 435                 return self.__get_result()
	      436             else:
	      437                 raise TimeoutError()
	  
	  /usr/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
	      382     def __get_result(self):
	      383         if self._exception:
	  --> 384             raise self._exception
	      385         else:
	      386             return self._result
	  
	  /usr/local/lib/python3.7/dist-packages/jupyter_ui_poll/_poll.py in _poll_async(self, n)
	      120     async def _poll_async(self, n=1):
	      121         for _ in range(n):
	  --> 122             await self.do_one_iteration()
	      123 
	      124     async def __aenter__(self):
	  
	  /usr/local/lib/python3.7/dist-packages/jupyter_ui_poll/_poll.py in do_one_iteration(self)
	      104     async def do_one_iteration(self):
	      105         try:
	  --> 106             await self._kernel.do_one_iteration()
	      107             # reset stdio back to original cell
	      108             self._reset_output()
	  
	  TypeError: object NoneType can't be used in 'await' expression
	  ```

    It looks like in Colab, `do_one_iteration` is not a coroutine. The following evaluates to `True` in JupyterLab but `False` in Colab.

	  ```py
	  from asyncio import iscoroutinefunction
	  iscoroutinefunction(get_ipython().kernel.do_one_iteration)
	  ```

**Comment by kylebarron** [comment]
I'm doing some exploration on [this branch](https://github.com/Kirill888/jupyter-ui-poll/compare/develop...kylebarron:kyle/colab-support?expand=1). Though testing this now in Colab I get a weird `ValueError: signal only works in main thread`. Any ideas?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-34af5bb52bd8> in <module>()
      6     while int(btn.description) < 10:
      7         print(btn.description, end="")
----> 8         ui_poll(11)  # Process upto 11 ui events per iteration
      9         time.sleep(0.1)
     10 

13 frames
/usr/local/lib/python3.7/dist-packages/jupyter_ui_poll/_async_thread.py in sync_func(*args, **kwargs)
     40     def wrap(self, func):
     41         def sync_func(*args, **kwargs):
---> 42             return self.submit(func, *args, **kwargs).result()
     43 
     44         return sync_func

/usr/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/usr/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/usr/local/lib/python3.7/dist-packages/jupyter_ui_poll/_poll.py in _poll_async(self, n)
    124     async def _poll_async(self, n=1):
    125         for _ in range(n):
--> 126             await self.do_one_iteration()
    127 
    128     async def __aenter__(self):

/usr/local/lib/python3.7/dist-packages/jupyter_ui_poll/_poll.py in do_one_iteration(self)
    107                 await self._kernel.do_one_iteration()
    108             else:
--> 109                 self._kernel.do_one_iteration()
    110         except QueueEmpty:
    111             # it's probably a bug in ipykernel,

/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py in do_one_iteration(self)
    296         for stream in self.shell_streams:
    297             # handle at most one request per iteration
--> 298             stream.flush(zmq.POLLIN, 1)
    299             stream.flush(zmq.POLLOUT)
    300 

/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py in flush(self, flag, limit)
    349             s, event = events[0]
    350             if event & zmq.POLLIN:  # receiving
--> 351                 self._handle_recv()
    352                 count += 1
    353                 if self.socket is None:

/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py in _handle_recv(self)
    479             if self._recv_callback:
    480                 callback = self._recv_callback
--> 481                 self._run_callback(callback, msg)
    482 
    483     def _handle_send(self):

/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py in _run_callback(self, callback, *args, **kwargs)
    429             # Use a NullContext to ensure that all StackContexts are run
    430             # inside our blanket exception handler rather than outside.
--> 431             callback(*args, **kwargs)
    432         except Exception:
    433             gen_log.error("Uncaught exception in ZMQStream callback", exc_info=True)

/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py in null_wrapper(*args, **kwargs)
    298                 current_state = _state.contexts
    299                 _state.contexts = cap_contexts[0]
--> 300                 return fn(*args, **kwargs)
    301             finally:
    302                 _state.contexts = current_state

/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py in dispatcher(msg)
    281         def make_dispatcher(stream):
    282             def dispatcher(msg):
--> 283                 return self.dispatch_shell(stream, msg)
    284             return dispatcher
    285 

/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py in dispatch_shell(self, stream, msg)
    229         else:
    230             self.log.debug("%s: %s", msg_type, msg)
--> 231             self.pre_handler_hook()
    232             try:
    233                 handler(stream, idents, msg)

/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py in pre_handler_hook(self)
    244         """Hook to execute before calling message handler"""
    245         # ensure default_int_handler during handler call
--> 246         self.saved_sigint_handler = signal(SIGINT, default_int_handler)
    247 
    248     def post_handler_hook(self):

/usr/lib/python3.7/signal.py in signal(signalnum, handler)
     45 @_wraps(_signal.signal)
     46 def signal(signalnum, handler):
---> 47     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
     48     return _int_to_enum(handler, Handlers)
     49 

ValueError: signal only works in main thread
```

**Comment by Kirill888** [comment]
Thanks for the report @kylebarron my guess is that colab is using customized kernel of sorts, or just old? Making this lib robust across different kernel drivers out there will take some time. Some of this can be done in generic fashion, like not assuming that what is returned by `self._kernel.do_one_iteration()` can be awaited, other things, like stdio remapping might be harder to make work on all targets. I'll have a poke at it on Colab, don't usually use it.

**Comment by Kirill888** [comment]
So colab has `ipykernel==4.10.1` and I only tested 5 and 6 series. I guess that's why, is this fixed by google or can you safely update it?

**Comment by kylebarron** [comment]
> So colab has `ipykernel==4.10.1` and I only tested 5 and 6 series. I guess that's why, is this fixed by google or can you safely update it?

Ah nice catch.

Colab does allow you to update `ipykernel` but warns you that it's potentially unstable. After running a cell with `!pip install -U ipykernel` it allows pip to update the package but then provides a warning:

> WARNING: Upgrading `ipython`, `ipykernel`, `tornado`, `prompt-toolkit` or `pyzmq` can
> cause your runtime to repeatedly crash or behave in unexpected ways and is not
> recommended. If your runtime won't connect or execute code, you can reset it
> with "Factory reset runtime" from the "Runtime" menu.

Interestingly `jupyter-ui-poll` _does_ seem to work fine with ipykernel 6 in Colab (testing with your `Examples.ipynb`).

So the question might now be: do you have any interest in having this package support `ipykernel` v4? Any suggestions for how it might be supported?

**Comment by Kirill888** [comment]
I had a deeper look into this. 

1. For `ipykernel<5`, you CAN use older version of `jupyter-ui-poll==0.1.3`, but maybe not with `Run All`?
2. To support changes in `ipykernel>=6` I had to switch to async operation by default and use a separate thread to provide synchronous interface for backwards compatibility, this approach doesn't work with `ipykernel` 4 series as it assumes to be running in the main thread (use of signal handler functions).

So changes in your branch @kylebarron, while valid won't be enough to make latest version of `jupyter-ui-poll` work with 4.xx series of `ipykernel`. Since older version of `jupyter-ui-poll` somewhat works on colab as far as I can tell, and one can also upgrade colab to newer ipykernel I think I won't bother trying to support `ipykernel` that is 2 major versions behind (released Aug 2019) in the current version of this library.

**Comment by kylebarron** [comment]
> 2\. To support changes in `ipykernel>=6` I had to switch to async operation by default and use a separate thread to provide synchronous interface for backwards compatibility, this approach doesn't work with `ipykernel` 4 series as it assumes to be running in the main thread (use of signal handler functions).

👌 I was guessing it was something like this; that makes a lot of sense!

> I think I won't bother trying to support `ipykernel` that is 2 major versions behind (released Aug 2019) in the current version of this library.

👍 Sounds good! Since I want to use this from inside a library, and since I don't think I can declare to pip "install version 0.1.3 if ipykernel < 5 is installed; otherwise latest version" I'll probably vendor a copy of 0.1.3 and have a switch in my app that checks the ipykernel version and uses the relevant copy of `jupyter-ui-poll`.

Thanks for your help!

**Comment by kylebarron** [comment]
Also I just realized that ipykernel 4.x is the last version to support Python 2.7, so that probably explains why Colab hasn't upgraded yet.

**Comment by kylebarron** [comment]
> I'll probably vendor a copy of 0.1.3 and have a switch in my app that checks the ipykernel version and uses the relevant copy of `jupyter-ui-poll`.

Just for the record, this seems to work well, (even with `Run All`) with one change:
https://github.com/Kirill888/jupyter-ui-poll/blob/cf468169abfa8a0f213123d68e204837742aa0bd/jupyter_ui_poll/_poll.py#L15

changed to
```py
        if hasattr(kernel, '_aborting') and kernel._aborting:
```
since ipykernel v4 doesn't have an `_aborting` attribute.

**Comment by Kirill888** [comment]
Yeah I noticed that too, probably switching to something like below won't hurt

```python
if getattr(kernel, '_aborting', False):
    # ...
```

not sure what that means for `Run All` when there are exceptions in cells below, you don't really want to run more cells after one that failed to run to completion.
